version: '2'
services:
    bitlottery-app:
        image: bitlottery
        external_links:
            - bitlottery-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=BitLottery
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    bitlottery-mongodb:
        extends:
            file: mongodb.yml
            service: bitlottery-mongodb
