version: '2'
services:
    bitlottery_clean-app:
        image: bitlottery_clean
        external_links:
            - bitlottery_clean-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=BitLottery_clean
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    bitlottery_clean-mongodb:
        extends:
            file: mongodb.yml
            service: bitlottery_clean-mongodb
