version: '2'
services:
    bitlottery-mongodb:
        container_name: bitlottery-mongodb
        image: mongo:3.3.12
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/BitLottery/mongodb/:/data/db/
