version: '2'
services:
    bitlottery-mongodb:
        container_name: bitlottery-mongodb
        image: mongo:3.3.12
        ports:
            - "27017:27017"
        command: mongos --configdb bitlottery-mongodb-config
    bitlottery-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    bitlottery-mongodb-config:
        image: mongo:mongo:3.3.12
        container_name: bitlottery-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
