version: '2'
services:
    bitlottery_clean-mongodb:
        container_name: bitlottery_clean-mongodb
        image: mongo:3.3.12
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/BitLottery_clean/mongodb/:/data/db/
